# Generated by Django 5.1.6 on 2025-03-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_jobseekeruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekeruser',
            old_name='personal_email',
            new_name='email',
        ),
        migrations.AddField(
            model_name='jobseekeruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
