# Generated by Django 5.1.6 on 2025-03-11 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_jobseekeruser_is_active_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerGuestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
